hostname = asimov-143.svail.baidu.com
55.69 seconds	cmarkea/distilcamembert-base-sentiment	accuracy: 0.3972333333333333	f1: 0.2142757101696134
113.15 seconds	claudio75/xlm-roberta-base-finetuned-marc	accuracy: 0.3460666666666667	f1: 0.2761045356351407
108.80 seconds	lewtun/xlm-roberta-base-finetuned-marc	accuracy: 0.36656666666666665	f1: 0.29303326868788676
***ERROR***	model: H:philschmid/distilbert-base-multilingual-cased-sentiment	data: H:amazon_reviews_multi	eqn: classify: stars ~ review_title + review_body	splits: test	split: test	task: None	error: (<class 'RuntimeError'>, RuntimeError('CUDA error: device-side assert triggered\nCUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.'), <traceback object at 0x7fd1701ff4c0>)
108.34 seconds	lewtun/xlm-roberta-base-finetuned-marc-en	accuracy: 0.3621666666666667	f1: 0.28789163980331234
108.15 seconds	Giannipinelli/xlm-roberta-base-finetuned-marc-en	accuracy: 0.3548	f1: 0.2938378585416116
108.50 seconds	begar/xlm-roberta-base-finetuned-marc	accuracy: 0.35873333333333335	f1: 0.28756896050889974
***ERROR***	model: H:lewtun/roberta-base-bne-finetuned-amazon_reviews_multi	data: H:amazon_reviews_multi	eqn: classify: stars ~ review_title + review_body	splits: test	split: test	task: None	error: (<class 'RuntimeError'>, RuntimeError('CUDA error: device-side assert triggered\nCUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.'), <traceback object at 0x7f3a8688df80>)
***ERROR***	model: H:IsabellaKarabasz/roberta-base-bne-finetuned-amazon_reviews_multi	data: H:amazon_reviews_multi	eqn: classify: stars ~ review_title + review_body	splits: test	split: test	task: None	error: (<class 'RuntimeError'>, RuntimeError('CUDA error: device-side assert triggered\nCUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.'), <traceback object at 0x7ff310de2f40>)
***ERROR***	model: H:philschmid/distilbert-base-multilingual-cased-sentiment-2	data: H:amazon_reviews_multi	eqn: classify: stars ~ review_title + review_body	splits: test	split: test	task: None	error: (<class 'RuntimeError'>, RuntimeError('CUDA error: device-side assert triggered\nCUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.'), <traceback object at 0x7f07ed5e9440>)
